### ISSUE TITLE
Option to change pitch without changing speed

### ISSUE THREAD

**Issue by zafkiel-P** [Prime-arys/Speed-Pitch-changer-extension#1]
Hi,

I was looking for an extension in Firefox similar to this one I found on the Chrome Web Store, here: [Pitch shifter - HTML5 Video audio FX](https://chrome.google.com/webstore/detail/pitch-shifter-html5-video/mpmkclglcbkjchakihfpblainfncennj)

Would it be possible for your extension to provide support for changing the pitch of a video without changing the speed?

**Comment by Prime-arys** [comment]
It seems complicated, I'll look into it.

**Comment by LePtitJoNadeau** [comment]
https://chrome.google.com/webstore/detail/transpose-%E2%96%B2%E2%96%BC-pitch-%E2%96%B9-spee/ioimlbgefgadofblnajllknopjboejda?hl=en

This application do it.

**Comment by Prime-arys** [comment]
The latest commit 0888e57bf89f4afd2a8cb3f1cf46b7e83843d67c adds experimental support for this feature.

**Comment by zafkiel-P** [comment]
Hi, any update on whether this will be released to the public master build?

**Comment by Prime-arys** [comment]
I still have a few optimizations/tests to do,
I plan to make the release this summer.

**Comment by Prime-arys** [comment]
I've released version 1.4.0 which includes the feature, see ffad3ced160e3510f8324a1b27d010cdbfba0fed & [addon](https://addons.mozilla.org/fr/firefox/addon/speed-pitch-changer/)
Let me know if you find a problem.
