### ISSUE TITLE
The Quality 

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#13]
please fix the quality to high please and thank you and this is codey again it is so do you think you can update it or no because of the quality sounds like in the middle or low it does it's gotta be the high quality better quality it does and i am sorry to bother you again about that it's just that the quality has to be changed to high it does better quality it does

**Comment by Prime-arys** [comment]
I'm doing some research for the quality of the sound produced when using the "**pitch only**" buttons **(♭ and ♯)**
