### ISSUE TITLE
Fix Low And High Pitch goes back at the number zero once in a great while and add return pitch button 

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#21]
and hey prime arys would you give me a favor too can you fix the low and high pitch goes back at the number zero once in a great while and add the return pitch button so it does not go back at number zero pitch

**Comment by codeyr67** [comment]
and that's during when i listen to songs in low or high pitched it happens it does once in a great while it does

**Comment by Prime-arys** [comment]
On which sites does this occur ?

**Comment by codeyr67** [comment]
youtube

**Comment by codeyr67** [comment]
hey when are you gonna update the next new update of speed pitch changer do you know like tell me when because i can't wait for the new update i cannot because it needs better sound quality that's great as professional i do and it needs fine grained settings too it does like up to 0.99 octaves or cents it does and the sound quality has to sound perfect like sound and clear it does and also i decided that i wanted the high pitched fixed i do like when you tune upper it goes back to the original when tuning way upper it does at the end it does and do you think you could keep it chirping or squeaky instead of going back to the original voice and sound okay and you have to do that when the next new update comes out okay

**Comment by codeyr67** [comment]
and fix the sound quality too as great as professional sound and clear and please please please update it on june 4th this year 2024 okay

**Comment by codeyr67** [comment]
and actually for low pitch can you keep it with noise when lowering the pitch too like almost to thousands of semitones and please don't use the original voice at all okay

**Comment by codeyr67** [comment]
when lowering the pitch at the end

**Comment by Prime-arys** [comment]
> and hey prime arys would you give me a favor too can you fix the low and high pitch goes back at the number zero once in a great while and add the return pitch button so it does not go back at number zero pitch

I can't reproduce the problem on youtube, 
the speed effect (+-) and the dedicated pitch effect (♯♭) are not reset when playing a playlist or manually changing video.
Normally, the only way for these effects to be reset is to refresh the tab (F5).
