### ISSUE TITLE
Please Do a New Update for speed pitch changer

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#22]
hey prime arys do you think you can update speed pitch changer tommorow or no

**Comment by Prime-arys** [comment]
I can't make a new stable version yet, you can try using the current development version if you like.

**Comment by codeyr67** [comment]
and if it's the new version i'd rather try it i would

**Comment by Prime-arys** [comment]
> when are you gonna make a new update do you know and what is current development version mean

I'm developing this module in my spare time, so I don't know when I'll be able to submit a version I'm satisfied with.
 You can see the differences by looking at the titles and comments of the [commits](https://github.com/Prime-arys/Speed-Pitch-changer-extension/commits/main/)

**Comment by Prime-arys** [comment]
> and if it's the new version i'd rather try it i would

To try dev version: 
- download latest [main.zip](https://github.com/Prime-arys/Speed-Pitch-changer-extension/archive/refs/heads/main.zip)
- unzip it
- on your Firefox go to about:debugging (Settings -> Extensions and themes -> ⚙ -> Debug add-ons )
- then click on Load Temporary Add-on...
- select the `manifest.json` file inside the extracted 'main' folder

_you can click on 'remove' to get back to your previous installed version_

**Warning** 
bugs are expected

**Comment by codeyr67** [comment]
it does not work and i want to try the dev mode i do

**Comment by Prime-arys** [comment]
> it does not work and i want to try the dev mode i do

here a maybe clearer instruction with video : https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by codeyr67** [comment]
still don't know how to do it

**Comment by codeyr67** [comment]
and still does not work either it does not

**Comment by codeyr67** [comment]
hey prime arys the developer app still did not work it did not it says a non valid manifest.json file it says
