### ISSUE TITLE
Add 1.00 cents to speed pitch changer in the same update 

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#28]
hey prime arys do you think there is any possible way to add 1.00 cents you know fine tune settings in the same old update for speed pitch changer and please add that as a 3rd setting okay if not then add 1.00 cents in the 1.4.4. version then okay

**Comment by codeyr67** [comment]
and also makesure in the 1.4.4. makesure it has the high quality as great as professional too okay and makesure it does not revert to the original voice at the end with the high pitched okay and makesure you make the 1.4.4. after the day you make 1.4.3. okay

**Comment by codeyr67** [comment]
and the 1.4.4. version should have the best quality too like loud and clear like i said high quality as great as professional okay

**Comment by codeyr67** [comment]
yeah i do not like the one now i do not

**Comment by Prime-arys** [comment]
> hey prime arys do you think there is any possible way to add 1.00 cents you know fine tune settings in the same old update for speed pitch changer and please add that as a 3rd setting okay if not then add 1.00 cents in the 1.4.4. version then okay

What do you mean by "add 1.00 cents" ?
What should this affect ?
Is it related to the behavior of the "speed buttons" (➕➖), or to the behavior of the "pitch only buttons" (♯ ♭) ?

**Comment by codeyr67** [comment]
no to the behavior of the pitch only not the speed as a 3rd setting you know what it means fine tune settings it means

**Comment by codeyr67** [comment]
and please makesure it has the best quality too okay as great as a professional okay for version 1.4.4. like loud and clear okay and you have to make it after the day you make 1.4.3. okay and remember add 1.00 cents for pitch only as a 3rd setting okay not the speed and it's fine tune settings it is
