### ISSUE TITLE
Add new button to set playback rate based on specified amount of semitones 

### ISSUE THREAD

**Issue by SmileyAG** [Prime-arys/Speed-Pitch-changer-extension#4]
I really like that addon much! That really made half of songs to sound even more pleasurable than in original! 
But there is one thing that I am missing: setting the speed depending on how much semitones are specified

Example: if user inserting the `0.5` of semitone, then it sets the playback rate to **1.0293** (C++ code: `rate = 1 / std::pow(2, -0.5 / 12.0);`)

**Comment by Prime-arys** [comment]
I've added a way to do this (8218b11662f461a9d720891412c838fd27e68a36)
![screen1](https://github.com/Prime-arys/Speed-Pitch-changer-extension/assets/88397986/5aa748c3-bbab-445e-92d4-c35cc519549d)
![screen2](https://github.com/Prime-arys/Speed-Pitch-changer-extension/assets/88397986/6174b9da-eacd-4ed2-99c4-d6f39dc8d5fa)

**Comment by Prime-arys** [comment]
The new version 1.4.1 is out on mozilla addons store
