### ISSUE TITLE
"Preserve pitch" does not work

### ISSUE THREAD

**Issue by calichii** [Prime-arys/Speed-Pitch-changer-extension#5]
Firefox version :  122
Extension version : 1.4.1
Platform : Linux

"Preserve pitch" option does not work.

After activating the option, reloading the extension and restarting the browser: The text "Preserved pitch" is displayed, but the '+' and '-' buttons still modify the pitch as well as the tempo.

With the option activated, it is expected that changing the tempo will not alter the pitch of what is being played.

**Comment by Prime-arys** [comment]
The problem occurs with the most recent versions of Firefox
It's also affect some previous build like 1.3.1
I make a change : a713b3533ddcd5a1352d447265c0edcd6fefceb8

**Comment by Prime-arys** [comment]
I released the patch in 1.4.2 on mozilla addons store.

**Comment by calichii** [comment]
Thank you very much!!! I usually use the Chrome extension Transpose for these purposes, but I'd like to have one in Firefox, as it's my main browser. Hopefully this extension will catch up with Transpose in functionality and quality, thanks again and lots of encouragement!
