### ISSUE TITLE
Fix Quality to High, Change to cents for semitones option pitch option like -99 or +99 cents 

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#6]
**Infos**
Firefox version : _XXX_
Extension version : _X.X.X_
Platform : (Windows | MacOS | Linux)

**Describe the problem / bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
( If it happens all the time or only on one website...)

**Comment by Prime-arys** [comment]
Could you be more specific ?
Since I'm not a native English speaker, I had some difficulty understanding your comment on mozilla addons.
