### ISSUE TITLE
Fix High Pitch goes back to the original voice when tuning upper

### ISSUE THREAD

**Issue by codeyr67** [Prime-arys/Speed-Pitch-changer-extension#8]
**Infos**
Firefox version : _XXX_
Extension version : _X.X.X_
Platform : (Windows | MacOS | Linux)

**Describe the problem / bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
( If it happens all the time or only on one website...)

**Comment by Prime-arys** [comment]
Too high a value on the pitch-only buttons causes the "tonality spectrum" to be exceeded, resulting in a gradual return to the original tone _(for the # button)_.
_(For the ♭ button, this "mutes" the sound)_.

To correct this, a limit will have to be imposed, as you mentioned here #7
